lesson 5 part 1
tftp/skillbox.laravel pull request #1
Opened 2021-04-23 17:51 UTC by tftp

2021-04-24 04:13 UTC, selyakovadim requested changes

2021-04-24 04:13 UTC, selyakovadim commented on app/Http/Controllers/ArticlesController.php
> +        $atributes['published'] = (bool)request('published');
А как это вообще работает?

2021-04-24 04:13 UTC, selyakovadim commented on app/Http/Controllers/ArticlesController.php
> +        $article->where('code', $article->code)->delete();
Здесь у нас уже есть `$article` Можно просто вызвать `$article->delete();`

2021-04-24 04:13 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Это нужно делать на уровне роутинга https://laravel.com/docs/8.x/routing#available-router-methods

2021-04-24 04:13 UTC, selyakovadim commented on resources/views/articles/item.blade.php
> +    <a href='/articles/{{$article->code}}/edit' class='badge badge-secondary'>Изменить</a>
Здесь лучше использовать именованые роуты https://laravel.com/docs/8.x/helpers#method-route

2021-04-24 04:13 UTC, selyakovadim commented on resources/views/articles/edit.blade.php
> +    {{$title}}
Лучше сделать как по примеру https://laravel.com/docs/8.x/blade#layouts-using-template-inheritance

2021-04-24 04:13 UTC, selyakovadim commented on app/Http/Controllers/ArticlesController.php
> +        return redirect('/articles/' . $atributes['code'])->with('success', 'Статья изменена');
Лучше использовать редирект на именованый роут или action https://laravel.com/docs/8.x/redirects

2021-04-24 07:59 UTC, tftp commented on app/Http/Controllers/ArticlesController.php
> +        $atributes['published'] = (bool)request('published');
Это же ForRequest Validation взято отсюда https://laravel.com/docs/8.x/validation#form-request-validation - сначало запрос приходит через ArticleRequest где валидируется и возвращает массив отвалидированных значений.

2021-04-24 08:04 UTC, tftp commented on app/Http/Controllers/ArticlesController.php
> +        $article->where('code', $article->code)->delete();
Пробовал, нельзя, выдает ошибку SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: delete from `articles` where `id` is null), без where('code', $article->code) пытается составить sql запрос через id, которого нет.

2021-04-24 08:29 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Здесь не понятно, ничего. Где делать? В web.php? Но нам же нужно валидацию сделать (а именно в зависимости от метода разная валидация будет для 'code'. А в задании написано, что нужно в Form Request прописать.

2021-04-25 05:24 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
А зачем делать такой костыль и проверять какой у нас метод? Можно же реализовать два FormRequest, например `StoreArticleRequest` и `UpdateArticleRequest`

2021-04-25 05:24 UTC, selyakovadim commented on app/Http/Controllers/ArticlesController.php
> +        $article->where('code', $article->code)->delete();
Первичный ключ лучше добавить потому что наверняка мы заходим наши статьи связывать с другими сущностями. Например с комментариями или тегами/категориями.

2021-04-25 05:30 UTC, selyakovadim commented on app/Http/Controllers/ArticlesController.php
> +        $atributes['published'] = (bool)request('published');
Да, всё верно

2021-04-25 07:28 UTC, tftp commented on app/Http/Controllers/ArticlesController.php
> +        $article->where('code', $article->code)->delete();
Добавил первичный ключ. Убрал where('code', $article->code).

2021-04-25 07:34 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Реализовал оба FormRequest, единственно проблема может быть если при изменении статьи поменять код, на тот, который будет совпадать с каким нибудь из других статей. Но здесь пока не знаю, как обойти.

2021-04-25 07:34 UTC, tftp commented on resources/views/articles/item.blade.php
> +    <a href='/articles/{{$article->code}}/edit' class='badge badge-secondary'>Изменить</a>
изменил

2021-04-25 07:34 UTC, tftp commented on resources/views/articles/edit.blade.php
> +    {{$title}}
изменил

2021-04-25 07:34 UTC, tftp commented on app/Http/Controllers/ArticlesController.php
> +        return redirect('/articles/' . $atributes['code'])->with('success', 'Статья изменена');
изменил

2021-04-25 07:45 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Можно почитать вот здесь https://laravel.com/docs/8.x/validation#rule-unique со слов "Forcing A Unique Rule To Ignore A Given ID"

2021-04-25 09:46 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
там нужно использовать объект $article: Rule::unique('articles')->ignore($article),
откуда его взять, как передать в FormRequest?

2021-04-25 10:38 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
https://laravel.com/docs/8.x/validation#:~:text=Also%2C%20note%20the,on%20the%20route

2021-04-25 11:29 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
это не пойдет, т.к. $this->route('article') вернет доступ к URI параметрам, а нужно объект модели Article

2021-04-25 11:34 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
сделал по другому  чуть, с валидацией в контроллере, сейчас скину

2021-04-25 12:49 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Это точно не решение потому что наша задача была вынести логику валидации в FormRequrst. Если вы заметите, то где я кидал был такой [пример](https://laravel.com/docs/8.x/validation#:~:text=Comment%3A%3Afind(%24this-%3Eroute(%27comment%27))%3B ). Или можно просто [передать](https://laravel.com/docs/8.x/validation#:~:text=unique(%27users%27)-%3Eignore(-,%24user-%3Eid,-)%2C%0A%20%20%20%20%5D%2C%0A%5D)%3B) в метод ignore id записи. Но делать это нужно с [осторожностью](https://laravel.com/docs/8.x/validation#:~:text=You%20should%20never,SQL%20injection%20attack.)

2021-04-25 12:53 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
не забудьте отправить задание на проверку в skillbox

2021-04-25 13:24 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Да я взял из этого примера решение, но там нужен именно объект, а я незнаю как его передать в FormRequest. С передачей id через форму понятно, что можно, но наверное не правильно, потому что пользователь может его исправить.

2021-04-25 13:26 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Остановимся пока на таком решении, или добавить в форму поле id?

2021-04-25 13:38 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Если у нас `$this->route('article')` возвращает `code`, то чтобы достать модель из базы нужно сделать такой запрос: `Article::where('code', $this->route('article'))->first();`

2021-04-25 14:12 UTC, tftp commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Я не знаю с чем это связано, но когда опять стал использовать $this->route('article') , то получил модель, то что и нужно. Но почему же раньше возвращало совсем другое... может что то неправильно писал!? А сейчас подхватил модель и работает нормально. Сейчас солью изменения.

2021-04-25 14:15 UTC, selyakovadim commented on app/Http/Requests/ArticleRequest.php
> +        $method = request('_method');
Магия

2021-04-25 14:30 UTC, merged